version: '3.8'
services:
  back-end:
    build:
      context: ./back-end
      dockerfile: Dockerfile
    image: softy-pinko-back-end:task5
    ports:
      - "5252"  # Internal port only
  front-end:
    build:
      context: ./front-end
      dockerfile: Dockerfile
    image: softy-pinko-front-end:task5
    ports:
      - "9000"  # Internal port only
    depends_on:
      - back-end
  proxy:
    build:
      context: ./proxy
      dockerfile: Dockerfile
    image: softy-pinko-proxy:task5
    ports:
      - "80:80"
    depends_on:
      - back-end
      - front-end
